apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: ms-ambulance-wl
  includeSelectors: true
  includeTemplates: true
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: porodnica-ambulance-home
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/ms-ambulance-ufe
- ../../../apps/porodnica-ambulance-ufe


components:
- ../../../components/version-release