apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ms-ambulance-ufe-content
spec:
  microFrontend: ms-ambulance-ufe
  element: ms-ambulance-wl-app
  attributes:
    - name: api-base
      value: /ms-api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ms-ambulance-wl(/.*)?$"
      