apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ms-ambulance-ufe-content
spec:
  microFrontend: ms-ambulance-ufe
  element: ms-ambulance-wl-app
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ms-ambulance-wl(/.*)?$"